### ISSUE TITLE
IDs on all Page H2s

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/kinderplatz.ookb.co#18]
7. Age Groups Section
a. Works OK on laptop, but on phone, section contents don’t jump to each topic content

>>>

Not just AgeGroups, make sure this is the case everywhere

**Comment by bjornmeansbear** [comment]
@AConati you reopened this; did you get them all? so far everything I've checked seems to be good

**Comment by AConati** [comment]
I think I got everything. Just wanted to make sure before I hid the issue. I'll close it.
